import Lean.Meta.Tactic.Simp
import Mathlib.Tactic.TypeStar

namespace SynthLean

variable (χ : Type*) in
/-- A HoTT0 expression with axioms indexed by `χ`. -/
inductive Expr where
  /-- An axiom (i.e., a closed term constant in the theory) of the given type. -/
  | ax (c : χ) (A : Expr)
  /-- De Bruijn index. -/
  | bvar (i : Nat)
  /-- Dependent product. -/
  | pi (l l' : Nat) (A B : Expr)
  /-- Lambda with the specified argument type. -/
  | lam (l l' : Nat) (A b : Expr)
  /-- Application at the specified output type family `B`. -/
  | app (l l' : Nat) (B fn arg : Expr)
  /-- Dependent sum. -/
  | sigma (l l' : Nat) (A B : Expr)
  /-- Pair formation. -/
  | pair (l l' : Nat) (B t u : Expr)
  /-- First component of a pair. -/
  | fst (l l' : Nat) (A B p : Expr)
  /-- Second component of a pair. -/
  | snd (l l' : Nat) (A B p : Expr)
  /-- Identity type. -/
  -- TODO: capitalize all the types
  | Id (l : Nat) (A t u : Expr)
  /-- A reflexive identity. -/
  | refl (l : Nat) (t : Expr)
  /-- Eliminates an identity. -/
  | idRec (l l' : Nat) (t M r u h : Expr)
  /-- A type universe. -/
  | univ (l : Nat)
  /-- Type from a code. -/
  | el (a : Expr)
  /-- Code from a type. -/
  | code (A : Expr)
  deriving Inhabited, Repr, Lean.ToExpr

namespace Expr

variable {χ χ' : Type*} (f : χ → χ')

@[simp]
theorem sizeOf_pos (e : Expr χ) : 0 < sizeOf e := by
  induction e <;> { dsimp; omega }

-- `Expr.map` can be autogenerated using `derive Functor`,
-- but the result is not sufficiently universe-polymorphic.
-- See https://leanprover.zulipchat.com/#narrow/channel/113489-new-members/topic/inferred.20Type.20universe.20in.20functors/near/217072636
def map : Expr χ → Expr χ'
  | ax c A => ax (f c) (map A)
  | bvar i => bvar i
  | pi l l' A B => pi l l' (map A) (map B)
  | lam l l' A b => lam l l' (map A) (map b)
  | app l l' B fn arg => app l l' (map B) (map fn) (map arg)
  | sigma l l' A B => sigma l l' (map A) (map B)
  | pair l l' B t u => pair l l' (map B) (map t) (map u)
  | fst l l' A B p => fst l l' (map A) (map B) (map p)
  | snd l l' A B p => snd l l' (map A) (map B) (map p)
  | Id l A t u => Id l (map A) (map t) (map u)
  | refl l t => refl l (map t)
  | idRec l l' t M r u h => idRec l l' (map t) (map M) (map r) (map u) (map h)
  | univ l => univ l
  | el a => el (map a)
  | code A => code (map A)

@[simp] theorem map_id_fun : map (id : χ → χ) = id := by
  funext e
  induction e <;> simp_all [map]

@[simp] theorem map_id_fun' : map (fun (c : χ) => c) = id := map_id_fun

end Expr

/-- A convergent rewriting system for the HoTT0 σ-calculus. -/
-- The attribute has to be initialized here for use in downstream modules.
register_simp_attr autosubst

end SynthLean
